### ISSUE TITLE
No devices returned

### ISSUE THREAD

**Issue by chrisbsmith** [peckrob/nest-watch#3]
Are you still getting devices returned?  

```php
$devices = $nest->getDevices('thermostat');
```

This isn't returning any data for me.

**Comment by ncareau** [comment]
Are you using an account that is not the master account ? I believe there is a limitation in place when using the public API that only a master account has access to the device.

**Comment by chrisbsmith** [comment]
Thanks @ncareau I just found that out.  I had created a second account in hopes of not having to use my primary account info but didn't get any data.  Just tried my master account and it worked.  Should've tried that first I guess.
